services:
  gss-api:
    container_name: gss-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always
    env_file:
      - .env
    depends_on:
      gss-postgres-db:
        condition: service_healthy

  gss-postgres-db:
    container_name: gss-postgres-db
    image: postgres:13
    ports:
      - "5432:5432"
    restart: always
    env_file:
      - .env
    volumes:
      - ./volumes/gss-db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  gss-db:
    driver: local
